version: '3.8'

services:
  server:
    build: ./server
    ports:
      - 3000:3000
    depends_on:
      - postgres-db
    volumes:
      - ./server/:/usr/src/app
    environment:
      - NODE_ENV=production
      # - NODE_ENV=development
  postgres-db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres/postgres-db-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  client:
    build: ./client
    ports:
      - 4000:4000
    volumes:
      - ./client/:/usr/src/app
    depends_on:
      - server

volumes:
  postgres-data: {}