# databases:
#   - name: postgres-db
#     databaseName: postgres-db
#     user: postgres

databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: app-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
  - type: web
    name: app-client
    env: docker
    dockerfilePath: ./client/Dockerfile
