version: '3.8'

services:
  postgres-db-test:
    image: postgres
    ports:
      - 5434:${DB_PORT}
    volumes:
      - ./postgres/test/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DB_USER_DEV}
      - POSTGRES_PASSWORD=${DB_PASSWORD_DEV}
      - POSTGRES_DB=${DB_NAME_TEST}