version: '3.8'

services:
  server:
    image: twit-dev-server
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres-db-dev
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
  postgres-db-dev:
    image: postgres
    ports:
      - 5433:${DB_PORT}
    volumes:
      - ./postgres-dev-data:/data/db
      - ./postgres/dev/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DB_USER_DEV}
      - POSTGRES_PASSWORD=${DB_PASSWORD_DEV}
      - POSTGRES_DB=${DB_NAME_DEV}

volumes:
  postgres-dev-data: {}