# fly.toml app configuration file generated for social-app-twitter-clone on 2023-08-09T12:25:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "social-app-twitter-clone"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = 3000
  NODE_ENV = "production"
